### ISSUE TITLE
Redefinition of Modules compile error in Xcode 11.2

### ISSUE THREAD

**Issue by nschucky** [AckeeCZ/iOS-MVVM-ProjectTemplate#38]
I'm getting compile errors when trying to build in Xcode 11.2, has anyone experienced this issue?
<img width="280" alt="Screen Shot 2019-11-29 at 10 38 07 AM" src="https://user-images.githubusercontent.com/11652045/69885897-678d6180-1294-11ea-9be8-0a72f516aa62.png">

**Comment by olejnjak** [comment]
Hi @nschucky,

I'm not sure that we experienced such issue, will try and report back soon 😉

**Comment by olejnjak** [comment]
Hi, actually the current `master` is not compilable at least from different reason in Xcode 11.2, in `Cartfile.resolved` we depend on `ReactiveCococa 10.0.0` which is not compilable with Carthage. I'll start a dependency update branch and close this issue when it is ready

**Comment by olejnjak** [comment]
Well after merging #37 which also contains Xcode version update, current `master` seems to work just fine.

```
git clone git@github.com:AckeeCZ/iOS-MVVM-ProjectTemplate
bundle install
bundle exec pod install
carthage bootstrap --platform iOS --cache-builds
```

The project seems to be compilable just fine.

Let us know if you run into any more issues 😎
